export const Resources = [
    ['background', 'res/background.png'],
    ['land', 'res/land.png'],
    ['pencilLeft', 'res/pie_left.png'],
    ['pencilRight', 'res/pie_right.png'],
    ['birdsToLeft', 'res/birds_to_left.png'],
    ['birdsToRight', 'res/birds_to_right.png'],
    ['title', 'res/title.png'],
    ['ready', 'res/ready.png'],
    ['start', 'res/start.png'],
    ['rank', 'res/rank.png'],
    ['share', 'res/share.png'],
    ['return', 'res/return.png'],
    ['new', 'res/new.png'],
    ['medal0', 'res/medal_0.png'],
    ['medal1', 'res/medal_1.png'],
    ['medal2', 'res/medal_2.png'],
    ['medal3', 'res/medal_3.png'],
    ['message', 'res/message.png'],
    ['info', 'res/info.png'],
    ['gameOver', 'res/game_over.png'],
    ['zero', 'res/0.png'],
    ['one', 'res/1.png'],
    ['two', 'res/2.png'],
    ['three', 'res/3.png'],
    ['four', 'res/4.png'],
    ['five', 'res/5.png'],
    ['six', 'res/6.png'],
    ['seven', 'res/7.png'],
    ['eight', 'res/8.png'],
    ['nine', 'res/9.png'],
];

